"""
Django settings for netology_pd_diplom project.

Generated by 'django-admin startproject' using Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Hawk Configuration
# Получите токен в личном кабинете Hawk (не DSN, а именно токен!)
HAWK_TOKEN = os.environ.get('HAWK_TOKEN', 'ваш_токен')

if HAWK_TOKEN:
    # Импортируем функцию инициализации
    from backend.hawk_setup import init_hawk, hawk_before_send
    
    # Инициализируем Hawk и сохраняем в глобальную переменную
    hawk = init_hawk(
        token=HAWK_TOKEN,
        collector_endpoint='https://k1.hawk.so',
        release=os.environ.get('HAWK_RELEASE', '1.0.0'),
        before_send=hawk_before_send,
    )
    print(f"✓ Hawk initialized with token: {HAWK_TOKEN[:10]}...")
else:
    print("✗ Hawk token not set - monitoring disabled")
    hawk = None

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '=hs6$#5om031nujz4staql9mbuste=!dc^6)4opsjq!vvjxzj@'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition
INSTALLED_APPS = [
    'baton',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',  # Добавить для social-auth
    'rest_framework',
    'rest_framework.authtoken',
    'django_rest_passwordreset',
    'imagekit',
    'cacheops',
    'drf_spectacular',  
    'drf_spectacular_sidecar',
    # Social Auth
    'social_django',  
    'backend',
    'baton.autodiscover',
]

BATON = {
    'SITE_HEADER': 'Netology Diplom Admin',
    'SITE_TITLE': 'Netology Admin',
    'INDEX_TITLE': 'Управление проектом',
    'SUPPORT_HREF': 'https://github.com/ваш-репозиторий/issues',
    'COPYRIGHT': 'copyright © 2025 <a href="https://ваш-сайт.ru">Ваша компания</a>',
    'POWERED_BY': '<a href="https://ваш-сайт.ru">Ваша компания</a>',
    'CONFIRM_UNSAVED_CHANGES': True,
    'SHOW_MULTIPART_UPLOADING': True,
    'ENABLE_IMAGES_PREVIEW': True,
    'CHANGELIST_FILTERS_IN_MODAL': True,
    'CHANGEFORM_FIXED_SUBMIT_ROW': True,
    'MENU_TITLE': 'Меню',
    'GRAVATAR_ENABLED': True,
    'FORCE_THEME': 'light',  # или 'dark'
    
    # Настройка меню админки
    'MENU': (
        {'type': 'title', 'label': 'Основные разделы', 'apps': ('backend',), 'icon': 'apps'},
        {
            'type': 'app',
            'name': 'backend',
            'label': 'Магазин',
            'icon': 'store',
            'models': (
                {'name': 'user', 'label': 'Пользователи', 'icon': 'people'},
                {'name': 'shop', 'label': 'Магазины', 'icon': 'storefront'},
                {'name': 'category', 'label': 'Категории', 'icon': 'category'},
                {'name': 'product', 'label': 'Товары', 'icon': 'inventory'},
                {'name': 'order', 'label': 'Заказы', 'icon': 'shopping_cart'},
                {'name': 'contact', 'label': 'Контакты', 'icon': 'contacts'},
            )
        },
        {'type': 'title', 'label': 'Аутентификация', 'apps': ('auth',), 'icon': 'security'},
        {
            'type': 'app',
            'name': 'auth',
            'label': 'Аутентификация',
            'icon': 'lock',
            'models': (
                {'name': 'user', 'label': 'Пользователи Django', 'icon': 'people'},
                {'name': 'group', 'label': 'Группы', 'icon': 'groups'},
            )
        },
        {
            'type': 'free',
            'label': 'Внешние ссылки',
            'icon': 'link',
            'children': [
                {'type': 'free', 'label': 'Swagger UI', 'url': '/api/schema/swagger-ui/', 'icon': 'api'},
                {'type': 'free', 'label': 'ReDoc', 'url': '/api/schema/redoc/', 'icon': 'description'},
                {'type': 'free', 'label': 'GitHub', 'url': 'https://github.com', 'icon': 'code'},
            ]
        },
    )
}

# ========== НАСТРОЙКИ КЭШИРОВАНИЯ ==========
# Используем in-memory cache вместо Redis
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
        'TIMEOUT': 60 * 60,  # 1 час
    }
}

# Настройки cacheops - используем Django cache backend
CACHEOPS_CACHE = 'default'  # Используем стандартный кэш Django
CACHEOPS_DEFAULTS = {
    'timeout': 60 * 60  # 1 час по умолчанию
}

# Стратегия кэширования для разных моделей
CACHEOPS = {
    # Кэшировать все get запросы для моделей пользователей
    'auth.user': {'ops': 'get', 'timeout': 60*15},
    
    # Кэшировать все запросы для моделей магазина
    'backend.category': {'ops': 'all', 'timeout': 60*60},
    'backend.shop': {'ops': 'all', 'timeout': 60*60},
    'backend.product': {'ops': 'all', 'timeout': 60*60},
    'backend.productinfo': {'ops': ('fetch', 'get'), 'timeout': 60*60},
    
    # Для всех остальных моделей разрешаем ручное кэширование
    '*.*': {'timeout': 60*60},
}

# Не останавливать приложение при ошибках кэширования
CACHEOPS_DEGRADE_ON_FAILURE = True
# ========== КОНЕЦ НАСТРОЕК КЭШИРОВАНИЯ ==========

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # Social Auth middleware 
    'backend.middleware.HawkMiddleware',
    'social_django.middleware.SocialAuthExceptionMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Site ID для django.contrib.sites
SITE_ID = 1

# Аутентификация
AUTHENTICATION_BACKENDS = [
    'social_core.backends.google.GoogleOAuth2',
    'social_core.backends.github.GithubOAuth2',
    'django.contrib.auth.backends.ModelBackend',
]

# Настройки Social Auth
SOCIAL_AUTH_URL_NAMESPACE = 'social'

# Ключи приложений
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = os.environ.get('GOOGLE_OAUTH2_KEY', '')
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = os.environ.get('GOOGLE_OAUTH2_SECRET', '')
SOCIAL_AUTH_GITHUB_KEY = os.environ.get('GITHUB_KEY', '')
SOCIAL_AUTH_GITHUB_SECRET = os.environ.get('GITHUB_SECRET', '')

# Дополнительные настройки Social Auth
SOCIAL_AUTH_LOGIN_REDIRECT_URL = '/api/v1/social/login/success/'
SOCIAL_AUTH_LOGIN_ERROR_URL = '/api/v1/social/login/error/'
SOCIAL_AUTH_NEW_USER_REDIRECT_URL = '/api/v1/social/login/success/'
SOCIAL_AUTH_NEW_ASSOCIATION_REDIRECT_URL = '/api/v1/social/login/success/'
SOCIAL_AUTH_CREATE_USERS = True
SOCIAL_AUTH_USER_FIELDS = ['email', 'first_name', 'last_name', 'username']
SOCIAL_AUTH_GOOGLE_OAUTH2_SCOPE = [
    'https://www.googleapis.com/auth/userinfo.email',
    'https://www.googleapis.com/auth/userinfo.profile',
]
SOCIAL_AUTH_GITHUB_SCOPE = ['user:email']

ROOT_URLCONF = 'netology_pd_diplom.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'netology_pd_diplom.wsgi.application'

# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_L10N = True
USE_TZ = True

# Static files
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

AUTH_USER_MODEL = 'backend.User'

# Email settings
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.mail.ru'
EMAIL_HOST_USER = 'netology.diplom@mail.ru'
EMAIL_HOST_PASSWORD = 'CLdm7yW4U9nivz9mbexu'
EMAIL_PORT = '465'
EMAIL_USE_SSL = True
SERVER_EMAIL = EMAIL_HOST_USER

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 40,
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/day',
        'user': '1000/day',
        'register': '5/hour',
        'login': '10/minute',
        'import': '10/day',
    },
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'EXCEPTION_HANDLER': 'backend.exceptions.hawk_exception_handler',
}

# Spectacular settings
SPECTACULAR_SETTINGS = {
    'TITLE': 'Netology Diplom API',
    'DESCRIPTION': 'API для дипломного проекта интернет-магазина',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'SWAGGER_UI_SETTINGS': {
        'deepLinking': True,
        'persistAuthorization': True,
        'displayOperationId': True,
    },
    'COMPONENT_SPLIT_REQUEST': True,
    'SCHEMA_PATH_PREFIX': '/api/v1',
}

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Celery Configuration
CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60
CELERY_RESULT_EXPIRES = 3600
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'
CELERY_TASK_ROUTES = {
    'backend.tasks.send_email_task': {'queue': 'email'},
    'backend.tasks.import_products_task': {'queue': 'import'},
    'backend.tasks.process_user_avatar': {'queue': 'images'},
    'backend.tasks.process_product_image': {'queue': 'images'},
}
CELERY_TASK_ALWAYS_EAGER = True
CELERY_TASK_EAGER_PROPAGATES = True